describe("Portfolio", () => {
  it("tests Portfolio", () => {
    cy.viewport(1640, 1066);
    cy.visit("http://localhost:5173/");
    cy.get("button.MuiButton-outlined").click();
    cy.get("#name").click();
    cy.get("#name").type("當");
    cy.get("#name").type("");
    cy.get("#name").type("fwfw");
    cy.get("#email").type("fwfw@");
    cy.get("#email").type("fwfw@gmail.com");
    cy.get("#password").type("Abcd1234!");
    cy.get("button").click();
    cy.get("div.MuiDialog-root a").click();
    cy.get("div.MuiCardContent-root").click();
    cy.get("#email").click();
    cy.get("#email").type("fwfw@gmail.com");
    cy.get("#password").type("A");
    cy.get("#password").type("A");
    cy.get("#password").type("Abcd1234!");
    cy.get("button").click();
    cy.get("#root > div button").click();
    cy.get("#root > div a").click();
    cy.get("a:nth-of-type(3)").click();
    cy.get("a:nth-of-type(4)").click();
    cy.get("a:nth-of-type(5)").click();
    cy.get("a:nth-of-type(6)").click();
    cy.get("#\\:r8f\\:").click();
    cy.get("#\\:r8f\\:").type("Santa");
    cy.get("#\\:r8h\\:").type("C");
    cy.get("#\\:r8h\\:").type("Claus");
    cy.get("#\\:r8j\\:").type("6471234567");
    cy.get("#\\:r8l\\:").type("S");
    cy.get("#\\:r8l\\:").type("Santa2025@");
    cy.get("#\\:r8l\\:").type("Santa2025@gmail.com");
    cy.get("#\\:r8n\\:").type("M");
    cy.get("#\\:r8n\\:").type("Merry C");
    cy.get("#\\:r8n\\:").type("Merry Christmas!!");
    cy.get("#root > div button").click();
    cy.get("header button").click();
    cy.get("button.MuiButton-contained").click();
    cy.get("#email").click();
    cy.get("#email").type("A");
    cy.get("#email").type("Admin");
    cy.get("#email").type("Admin@");
    cy.get("#email").type("Admin@gmail.com");
    cy.get("#password").type("A");
    cy.get("#password").type("Admin123@");
    cy.get("#password").type("Admin123!");
    cy.get("button").click();
    cy.get("a:nth-of-type(3)").click();
    cy.get("a:nth-of-type(4)").click();
    cy.get("#root > div > div > div:nth-of-type(1) button.MuiButton-textPrimary").click();
    cy.get("#\\:ra5\\:").click();
    cy.get("#\\:ra5\\:").click();
    cy.get("#\\:ra5\\:").dblclick();
    cy.get("#\\:ra5\\:").dblclick();
    cy.get("#\\:ra5\\:").click();
    cy.get("#\\:ra5\\:").click();
    cy.get("#\\:ra5\\:").click();
    cy.get("#\\:ra5\\:").click();
    cy.get("#\\:ra5\\:").type("Built a responsive React/Tailwind UI to view courses and events. Created reusable components, dark mode, basic accessibility checks.");
    cy.get("button.MuiButton-contained").click();
    cy.get("#\\:ra1\\:").click();
    cy.get("#\\:ra1\\:").type("T");
    cy.get("#\\:ra1\\:").type("Testing ");
    cy.get("#\\:ra3\\:").type("D");
    cy.get("#\\:ra3\\:").type("Developer");
    cy.get("#\\:ra5\\:").type("TG");
    cy.get("#\\:ra5\\:").type("Testing");
    cy.get("div.css-131uyni > label").click();
    cy.get("div.css-131uyni input").type("C:\\fakepath\\Screenshot 2025-12-05 140846.png");
    cy.get("#\\:ra9\\:").click();
    cy.get("#\\:ra9\\:").type("2025-12-25");
    cy.get("form button").click();
    cy.get("div:nth-of-type(4) button.MuiButton-textError").click();
    cy.get("a:nth-of-type(5)").click();
    cy.get("tr:nth-of-type(1) button.MuiButton-textPrimary").click();
    cy.get("#\\:rb7\\:").click();
    cy.get("#\\:rb7\\:").type("GPA: 4.36/4.5. Relevant: Advanced Database Concepts (SQL), Java, C#, Testing & QA, Software Systems Design, Web & Mobile App Development and Data Structures.");
    cy.get("button.MuiButton-contained").click();
    cy.get("#\\:rav\\:").click();
    cy.get("#\\:rav\\:").type("Education");
    cy.get("#\\:rb1\\:").type("T");
    cy.get("#\\:rb1\\:").type("Testing");
    cy.get("#\\:rb3\\:").type("Te");
    cy.get("#\\:rb3\\:").type("Testing");
    cy.get("#\\:rb5\\:").click();
    cy.get("#\\:rb5\\:").type("2026-01-01");
    cy.get("#\\:rb7\\:").click();
    cy.get("#\\:rb7\\:").type("T");
    cy.get("#\\:rb7\\:").type("Testing");
    cy.get("form button").click();
    cy.get("tr:nth-of-type(3) button.MuiButton-textPrimary").click();
    cy.get("tr:nth-of-type(3) button.MuiButton-textError").click();
    cy.get("a:nth-of-type(6)").click();
    cy.get("div:nth-of-type(3)").click();
    cy.get("a:nth-of-type(7)").click();
    cy.get("tbody > tr").click();
    cy.get("html").click();
    cy.get("#root > div button").click();
    cy.get("a:nth-of-type(8)").click();
    cy.get("tbody > tr:nth-of-type(1)").click();
    cy.get("tr:nth-of-type(2) > td:nth-of-type(4)").click();
    cy.get("tr:nth-of-type(2) button.MuiButton-textPrimary").click();
    cy.get("#root > div").click();
    cy.get("#\\:rbt\\:").type("S");
    cy.get("#\\:rbt\\:").type("Santa C");
    cy.get("#\\:rbt\\:").type("Santa Claus");
    cy.get("form").click();
    cy.get("button.MuiButton-contained").click();
    cy.get("#root > div").click();
    cy.get("header button").click();
  });
});
//# recorderSourceMap=BCBDBEBFBGAGAGBHAHAHAHBIAIAIAIAIBJAJAJBKAKBLALALALALALALALALBMAMBNBOBPBQBRARARBSASBTATBUAUBVBWBXBYBZBaBbBcBdAdAdBeAeBfAfAfBgBAgBAgBBhBAhBBiBAiBBjBAjBAjBBkBAkBBlBAlBBmBBnBBoBBpBBqBBrBArBBsBAsBAsBBtBAtBAtBBuBAuBAuBBvBAvBBwBAwBBxBByBBzBB0BB1BB2BB3BB4BB5BB6BB7BB8BB9BB+BB/BBgCBhCAhCBiCAiCAiCBjCAjCBkCAkCAkCBlCAlCBmCBnCBoCBpCBqCBrCBsCBtCBuCBvCBwCBxCByCBzCAzCAzCB0CA0CB1CA1CA1CB2CA2CB3CB4CB5CB6CB7CA7CB8CB9CB+CB/CBgDBhDBiDBjDBkDBlDBmDBnDBoDBpDBqDBrDArDBsDAsDBtDBuDBvDBwDB
